<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hemlata" failures="1" tests="2" name="ErrorValidationTest" time="5.922" errors="0" timestamp="2024-04-24T18:40:13 IST">
  <testcase classname="com.practicepom.ErrorValidation" name="LoginErrorValidation" time="3.814"/>
  <testcase classname="com.practicepom.ErrorValidation" name="StandAloneTest" time="0.003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.practicepom.ErrorValidation.StandAloneTest(ErrorValidation.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- StandAloneTest -->
</testsuite> <!-- ErrorValidationTest -->
